[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://sjbgskicxkpprstvdnvr.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqYmdza2ljeGtwcHJzdHZkbnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTkzMjQsImV4cCI6MjA2Njc3NTMyNH0.0ohhQVp-mQJ5tp-tp7TuBarsn7hQ-X5tjeHh6roDt0s"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200